[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
bridge = "FaWcnbmoyN1SWfUaio4cJAC2HokPgukzKhhk1hZrh4De"

[programs.devnet]
bridge = "FaWcnbmoyN1SWfUaio4cJAC2HokPgukzKhhk1hZrh4De"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"
bind_address = "127.0.0.1"
rpc_port = 8899
