/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthBridge__factory } from './EthBridge__factory.js';
export { TestToken__factory } from './TestToken__factory.js';